runtime: custom
env: flex

service: symfony3

runtime_config:
  document_root: web

beta_settings:
  cloud_sql_instances: chingor-php-gcs:us-central1:php-test-apps

env_variables:
  DB_SOCKET: /cloudsql/chingor-php-gcs:us-central1:php-test-apps
  DB_USERNAME: blog
  DB_PASSWORD: blog
  DB_DATABASE: blog
