runtime: custom
env: flex

service: wordpress

beta_settings:
  cloud_sql_instances: chingor-php-gcs:us-central1:php-test-apps

runtime_config:
  document_root: wordpress

env_variables:
  WHITELIST_FUNCTIONS: escapeshellarg,escapeshellcmd,exec,pclose,popen,shell_exec,phpversion,php_uname
  IS_BATCH_DAEMON_RUNNING: true
