runtime: php
env: flex

service: laravel

runtime_config:
  document_root: public

env:
  DB_SOCKET: /cloudsql/chingor-php-gcs:us-central1:php-test-apps
  DB_USERNAME: blog
  DB_PASSWORD: blog
  DB_DATABASE: blog
